included:
  - FlowDelivery

excluded:
  - Pods
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_parameter_alignment_on_call

disabled_rules:
  - todo
  - trailing_whitespace

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300

file_length:
  warning: 500
